//
//  Calendar.h
//  New Earth
//
//  Created by Scott Alexander on 4/14/17.
//  Copyright © 2017 Big Dog Tools. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "UnitInventory.h"
#import "NENotification.h"
#import "NeNotifications.h"
#import "Globals.h"
//#import "AppDelegate.h"

extern NSString* const kCalendarBeginChangesNotification;
extern NSString* const kCalendarInsertEntryNotification;
extern NSString* const kkCalendarDeleteEntryNotification;
extern NSString* const kCalendarChangesCompleteNotification;
extern NSString* const kCalendarGameOverNotification;

// to access data in the notifications
extern NSString* const kCalendarNotificationIndexPathKey;

@interface NECalendar : NSObject

@property bool firstBonus; // awarded bonus if have 25 laborers by 320 days
@property bool secondBonus; // awarded bonus in have 50 laborers by 639 days
@property bool thirdBonus; // awarded bonus in have 75 laborers by 958 days
@property bool fourthBonus; // awarded bonus in have 100 laborers by 1178 days

@property CGFloat firstPayment; // awarded first payment once 25 laborers and 365 days passed
@property CGFloat secondPayment; // awarded second payment once 50 laborers and 730 days passed

@property bool onSchedule; // true if on schedule (will limit negative notices) false give nags
@property bool farBehindSchedule; // true if onSchedule=no for too long will make many negative notices, more nags, more demanding

@property UnitInventory* theWarehouse;
@property NENotification* theMessage; // message generated by this class
@property NSMutableArray* milestoneList;
@property (strong, nonatomic) NewEarthGlobals* myGlobals;
@property (strong, nonatomic) NeNotifications* neNotes;

//-(float)checkTheCalendarOnDay:(int) theDay withLabor: (int) theLaborers;
-(void) performanceOnDay: (int) thisDay withMySettlers: (int) settlers;
+(id)sharedSelf;

@end
